version: '2'
services:
  beetbox:
    build: .beetbox
    ports:
      - "80:80"
    links:
      - db
    volumes_from:
      - data
  db:
    image: mariadb
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=beetbox
     - MYSQL_USER=beetbox
     - MYSQL_PASSWORD=beetbox
  data:
    image: beet/box
    volumes:
      - .:/var/beetbox
